import { NextResponse } from 'next/server';

const MASTRA_API_URL = 'http://localhost:4111';
const THREAD_ID = 'example-user-id'; // replace by a uuid generated by the front-end.
const RESOURCE_ID = 'weather-chat'; // replace by user id

function parseAISDKToMastra(params:  any) {
  const messages = params.messages?.map((msg: any) => ({
    role: msg.role,
    content: msg.parts?.map((part: any) => ({
      type: part.type,
      text: part.text
    })) || []
  })) || [];

  return {
    id: params.id || crypto.randomUUID(),
    messages, 
    trigger: params.trigger || "submit-message"
  };
}

export async function POST(req: Request) {
  const params = await req.json();

  try {
    // @TODO: add nutri-ia agent to backend :)
    const mastraPayload = parseAISDKToMastra(params);

    const response = await fetch(`${MASTRA_API_URL}/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'accept': 'text/event-stream',
      },
      body: JSON.stringify(mastraPayload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Mastra API error:', response.status, errorText);
      throw new Error(`Mastra API error: ${response.status}`);
    }

    // Check if the request signal is aborted
    req.signal.addEventListener('abort', () => {
      console.log('## Client aborted the request ##');
    });

    // Forward the stream directly - the AI SDK will handle the parsing
    return new Response(response.body, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    });
  } catch (error) {
    console.error('Error calling Mastra API:', error);
    return NextResponse.json(
      { error: 'Failed to communicate with Mastra API' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const response = await fetch(
      `${MASTRA_API_URL}/agents/nutri-ia/memory?threadId=${THREAD_ID}&resourceId=${RESOURCE_ID}`,
      {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!response.ok) {
      if (response.status === 404) {
        console.log('## not found chats ##', response.status);
        return NextResponse.json([]);
      }
      throw new Error(`Mastra API error: ${response.status}`);
    }

    const data = await response.json();
    return NextResponse.json(data.messages || []);
  } catch (error) {
    console.error('Error fetching messages from Mastra API:', error);
    return NextResponse.json([]);
  }
}