import { NextResponse } from 'next/server';

const MASTRA_API_URL = 'http://localhost:4111/api';
const THREAD_ID = 'example-user-id'; // replace by a uuid generated by the front-end.
const RESOURCE_ID = 'weather-chat'; // replace by user id

export async function POST(req: Request) {
  const params = await req.json();

  try {
    // @TODO: add nutri-ia agent to backend :)
    const response = await fetch(`${MASTRA_API_URL}/agents/nutri-ia/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...params,
        memory: {
          ...params.memory,
          thread: THREAD_ID,
          resource: RESOURCE_ID,
        }
      }),
    });

    if (!response.ok) {
      throw new Error(`Mastra API error: ${response.status}`);
    }

    return new Response(response.body, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    });
  } catch (error) {
    console.error('Error calling Mastra API:', error);
    return NextResponse.json(
      { error: 'Failed to communicate with Mastra API' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const response = await fetch(
      `${MASTRA_API_URL}/agents/nutri-ia/memory?threadId=${THREAD_ID}&resourceId=${RESOURCE_ID}`,
      {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!response.ok) {
      if (response.status === 404) {
        console.log('## not found chats ##', response.status);
        return NextResponse.json([]);
      }
      throw new Error(`Mastra API error: ${response.status}`);
    }

    const data = await response.json();
    return NextResponse.json(data.messages || []);
  } catch (error) {
    console.error('Error fetching messages from Mastra API:', error);
    return NextResponse.json([]);
  }
}