import { NextResponse } from 'next/server';

const MASTRA_API_URL = 'http://localhost:4111/api';
const THREAD_ID = 'example-user-id'; // replace by a uuid generated by the front-end.
const RESOURCE_ID = 'weather-chat'; // replace by user id

// Convert AI SDK messages (with parts) to Mastra format (with content)
function convertToMastraMessages(messages: any[]) {
  return messages.map(msg => ({
    role: msg.role,
    content: msg.parts?.map((part: any) => ({
      type: part.type,
      text: part.text
    })) || []
  }));
}

export async function POST(req: Request) {
  const params = await req.json();

  try {
    // Convert AI SDK messages to Mastra format
    const mastraMessages = convertToMastraMessages(params.messages || []);

    const mastraPayload = {
      id: params.id || crypto.randomUUID(),
      messages: mastraMessages,
      trigger: params.trigger || "submit-message"
    };

    console.log('## Sending to Mastra ##', JSON.stringify(mastraPayload, null, 2));

    const response = await fetch(`${MASTRA_API_URL}/agents/nutritionAnalystAgent/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'accept': 'text/event-stream',
      },
      body: JSON.stringify(mastraPayload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Mastra API error:', response.status, errorText);
      throw new Error(`Mastra API error: ${response.status}`);
    }

    // Transform Mastra SSE stream to AI SDK format
    const transformedStream = new ReadableStream({
      async start(controller) {
        const reader = response.body?.getReader();
        const decoder = new TextDecoder();
        const encoder = new TextEncoder();

        if (!reader) {
          controller.close();
          return;
        }

        let buffer = '';

        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() || '';

            for (const line of lines) {
              if (line.startsWith('data: ')) {
                const dataStr = line.slice(6);

                if (dataStr === '[DONE]') {
                  // Send finish message
                  controller.enqueue(encoder.encode(`2:${JSON.stringify({ finishReason: 'stop' })}\n`));
                  controller.close();
                  return;
                }

                try {
                  const data = JSON.parse(dataStr);

                  // Transform Mastra events to AI SDK format
                  if (data.type === 'text-delta' && data.payload?.text) {
                    // Send as data stream format: "0:{json}\n"
                    controller.enqueue(
                      encoder.encode(`0:${JSON.stringify({ type: 'text-delta', textDelta: data.payload.text })}\n`)
                    );
                  } else if (data.type === 'tool-call') {
                    controller.enqueue(
                      encoder.encode(`0:${JSON.stringify({
                        type: 'tool-call',
                        toolCallId: data.payload?.toolCallId,
                        toolName: data.payload?.toolName,
                        args: data.payload?.args
                      })}\n`)
                    );
                  } else if (data.type === 'tool-result') {
                    controller.enqueue(
                      encoder.encode(`0:${JSON.stringify({
                        type: 'tool-result',
                        toolCallId: data.payload?.toolCallId,
                        result: data.payload?.result
                      })}\n`)
                    );
                  }
                } catch (e) {
                  console.error('Failed to parse SSE data:', dataStr, e);
                }
              }
            }
          }

          controller.close();
        } catch (error) {
          console.error('Stream error:', error);
          controller.error(error);
        } finally {
          reader.releaseLock();
        }
      }
    });

    return new Response(transformedStream, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    });

  } catch (error) {
    console.error('Error calling Mastra API:', error);
    return NextResponse.json(
      { error: 'Failed to communicate with Mastra API' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const response = await fetch(
      `${MASTRA_API_URL}/agents/nutri-ia/memory?threadId=${THREAD_ID}&resourceId=${RESOURCE_ID}`,
      {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    if (!response.ok) {
      if (response.status === 404) {
        console.log('## not found chats ##', response.status);
        return NextResponse.json([]);
      }
      throw new Error(`Mastra API error: ${response.status}`);
    }

    const data = await response.json();
    return NextResponse.json(data.messages || []);
  } catch (error) {
    console.error('Error fetching messages from Mastra API:', error);
    return NextResponse.json([]);
  }
}
